# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Phase 3 - Storage Layer - Create iam groups and a deployment user for the project

Parameters:
  ProjectName:
    Type: String
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet for RDS"
      DBSubnetGroupName: !Join ["-", [!Ref "ProjectName", "DBSubnetGroup"]]
      SubnetIds:
        - Fn::ImportValue: !Join [":", [!Ref "ProjectName", "PublicSubnetOne"]]
        - Fn::ImportValue: !Join [":", [!Ref "ProjectName", "PublicSubnetTwo"]]

  PostgreSQLDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:
        !Join [
          "",
          ["{{resolve:secretsmanager:", !Ref "ProjectName", "::DB_NAME}}"],
        ]
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      DBSubnetGroupName: !Ref "DBSubnetGroup"
      DBInstanceIdentifier: !Ref "ProjectName"
      Engine: "postgres"
      EngineVersion: "12"
      MasterUsername:
        !Join [
          "",
          ["{{resolve:secretsmanager:", !Ref "ProjectName", "::DB_USER}}"],
        ]
      MasterUserPassword:
        !Join [
          "",
          ["{{resolve:secretsmanager:", !Ref "ProjectName", "::DB_PASSWORD}}"],
        ]
      MultiAZ: "false"
      PubliclyAccessible: "true"
      Port:
        !Join [
          "",
          ["{{resolve:secretsmanager:", !Ref "ProjectName", "::DB_PORT}}"],
        ]
      VPCSecurityGroups:
        - Fn::ImportValue: !Join [":", [!Ref "ProjectName", "DatabaseSG"]]
