# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Phase 3 - Storage Layer - Create the CICD resources (ECR)
Parameters:
  ProjectName:
    Type: String
  AppEnv:
    Type: String
Resources:
  CodePipelineServerBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName:
        !Join [
          "-",
          ["codepipeline", !Ref "ProjectName", !Ref "AppEnv", "server"],
        ]
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 7
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
      ObjectLockEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True

  CodePipelineClientBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName:
        !Join [
          "-",
          ["codepipeline", !Ref "ProjectName", !Ref "AppEnv", "client"],
        ]
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 7
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
      ObjectLockEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True

  CodePipelineGameResultServerBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName:
        !Join [
          "-",
          ["codepipeline", !Ref "ProjectName", !Ref "AppEnv", "gresult-server"],
        ]
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            ExpirationInDays: 7
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
      ObjectLockEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
