# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Phase 5 - CI/CD Layer - Create the CICD resources (ECR)
Parameters:
  ProjectName:
    Type: String

Resources:
  ServerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: Build the server application
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: build
          Status: ENABLED
          StreamName: server
      Name: !Join ["-", [!Ref "ProjectName", "server"]]
      ResourceAccessRole: !ImportValue "CodeBuildRoleArn"
      ServiceRole: !ImportValue "CodeBuildRoleArn"
      Source:
        BuildSpec: src/build/codebuild/buildspec.yml
        Type: CODEPIPELINE

  ClientBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: Build the client application
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: build
          Status: ENABLED
          StreamName: client
      Name: !Join ["-", [!Ref "ProjectName", "client"]]
      ResourceAccessRole: !ImportValue "CodeBuildRoleArn"
      ServiceRole: !ImportValue "CodeBuildRoleArn"
      Source:
        BuildSpec: src/build/codebuild/buildspec.yml
        Type: CODEPIPELINE

  GameResultServerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: Build the server application
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: build
          Status: ENABLED
          StreamName: game-result-server
      Name: !Join ["-", [!Ref "ProjectName", "game-result-server"]]
      ResourceAccessRole: !ImportValue "CodeBuildRoleArn"
      ServiceRole: !ImportValue "CodeBuildRoleArn"
      Source:
        BuildSpec: build/codebuild/buildspec.yml
        Type: CODEPIPELINE
