# @format

AWSTemplateFormatVersion: "2010-09-09"
Description: Phase 2 - Computer Layer - Create the app SSL certificates

Parameters:
  ProjectName:
    Type: String
  ServerDomainName:
    Type: String
  ClientDomainName:
    Type: String
  GameResultServerDomainName:
    Type: String

Resources:
  # Create dummy records first and then update them later after.
  # The load balancer has been created.
  ServerRoute53RecordForELB:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Join [":", [!Ref "ProjectName", "HostedZoneId"]]
      Name: !Ref "ServerDomainName"
      ResourceRecords: # Create a fake record first
        - 192.0.2.255
      TTL: 300
      Type: A

  ClientRoute53RecordForELB:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Join [":", [!Ref "ProjectName", "HostedZoneId"]]
      Name: !Ref "ClientDomainName"
      ResourceRecords: # Create a fake record first
        - 192.0.2.252
      TTL: 300
      Type: A

  GameResultServerRoute53RecordForELB:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: !Join [":", [!Ref "ProjectName", "HostedZoneId"]]
      Name: !Ref "GameResultServerDomainName"
      ResourceRecords: # Create a fake record first
        - 192.0.2.251
      TTL: 300
      Type: A
